const EXECUTION_RESULTS = {
    MATCH: "MATCH",
    MISMATCH: "MISMATCH",
    RUNTIME_ERROR: "RUNTIME_ERROR",
    COMPILATION_ERROR: "COMPILATION_ERROR",
    TLE: "TLE",
};

module.exports = {
    EXECUTION_RESULTS,
};
